dependencies:
  - libuuid
  - jq
  - conda-forge::lua>=5.3.4
  - python>=3.6
  - pycurl
  - pyyaml
  - pip
  - openssl
  - conda-forge::squashfs-tools
  - sphinx
  - git
  - flake8
  - pip:
    - nvchecker
    - ipdb
    - recommonmark
