channels:
  - conda-forge
dependencies:
  - jq
  - lua>=5.3.4
  - python>=3.6
  - pycurl
  - pyyaml
  - pip
  - openssl
  #! libuuid was included here for testing, possibly related to singularity?
  - pip:
    - nvchecker
    - ipdb
